require('seneca')()
    .use('entity')
    .use('dt')
    .listen( { type: 'tcp', port: 9000, pin: 'role:dt' } )
    .client( { type: 'tcp', port:9003, pin:'role:stats' } )
    .client( { type: 'tcp', port:9002, pin:'role:indexation' })